ALTER TABLE pms_track
    ADD COLUMN audio_feature_track_id VARCHAR(100),
    ADD COLUMN audio_feature_source VARCHAR(50) NOT NULL DEFAULT 'unresolved',
    ADD COLUMN audio_features_filled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN audio_analysis_url VARCHAR(300),
    ADD COLUMN audio_track_href VARCHAR(300),
    ADD COLUMN audio_track_uri VARCHAR(200),
    ADD COLUMN audio_feature_type VARCHAR(30) NOT NULL DEFAULT 'audio_features',
    ADD COLUMN audio_duration_ms INTEGER,
    ADD COLUMN audio_key INTEGER,
    ADD COLUMN audio_mode INTEGER,
    ADD COLUMN audio_time_signature INTEGER,
    ADD COLUMN audio_acousticness DOUBLE PRECISION,
    ADD COLUMN audio_danceability DOUBLE PRECISION,
    ADD COLUMN audio_energy DOUBLE PRECISION,
    ADD COLUMN audio_instrumentalness DOUBLE PRECISION,
    ADD COLUMN audio_liveness DOUBLE PRECISION,
    ADD COLUMN audio_loudness DOUBLE PRECISION,
    ADD COLUMN audio_speechiness DOUBLE PRECISION,
    ADD COLUMN audio_tempo DOUBLE PRECISION,
    ADD COLUMN audio_valence DOUBLE PRECISION,
    ADD COLUMN audio_resolved_at TIMESTAMPTZ;

UPDATE pms_track
SET
    audio_feature_track_id = spotify_track_id,
    audio_feature_source = spotify_audio_feature_source,
    audio_features_filled = spotify_audio_features_filled,
    audio_analysis_url = spotify_analysis_url,
    audio_track_href = spotify_track_href,
    audio_track_uri = spotify_uri,
    audio_feature_type = spotify_feature_type,
    audio_duration_ms = spotify_duration_ms,
    audio_key = spotify_key,
    audio_mode = spotify_mode,
    audio_time_signature = spotify_time_signature,
    audio_acousticness = spotify_acousticness,
    audio_danceability = spotify_danceability,
    audio_energy = spotify_energy,
    audio_instrumentalness = spotify_instrumentalness,
    audio_liveness = spotify_liveness,
    audio_loudness = spotify_loudness,
    audio_speechiness = spotify_speechiness,
    audio_tempo = spotify_tempo,
    audio_valence = spotify_valence,
    audio_resolved_at = spotify_resolved_at;

ALTER TABLE pms_imported_track
    ADD COLUMN audio_feature_track_id VARCHAR(100),
    ADD COLUMN audio_feature_source VARCHAR(50) NOT NULL DEFAULT 'unresolved',
    ADD COLUMN audio_features_filled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN audio_analysis_url VARCHAR(300),
    ADD COLUMN audio_track_href VARCHAR(300),
    ADD COLUMN audio_track_uri VARCHAR(200),
    ADD COLUMN audio_feature_type VARCHAR(30) NOT NULL DEFAULT 'audio_features',
    ADD COLUMN audio_duration_ms INTEGER,
    ADD COLUMN audio_key INTEGER,
    ADD COLUMN audio_mode INTEGER,
    ADD COLUMN audio_time_signature INTEGER,
    ADD COLUMN audio_acousticness DOUBLE PRECISION,
    ADD COLUMN audio_danceability DOUBLE PRECISION,
    ADD COLUMN audio_energy DOUBLE PRECISION,
    ADD COLUMN audio_instrumentalness DOUBLE PRECISION,
    ADD COLUMN audio_liveness DOUBLE PRECISION,
    ADD COLUMN audio_loudness DOUBLE PRECISION,
    ADD COLUMN audio_speechiness DOUBLE PRECISION,
    ADD COLUMN audio_tempo DOUBLE PRECISION,
    ADD COLUMN audio_valence DOUBLE PRECISION,
    ADD COLUMN audio_resolved_at TIMESTAMPTZ;

UPDATE pms_imported_track
SET
    audio_feature_track_id = spotify_track_id,
    audio_feature_source = spotify_audio_feature_source,
    audio_features_filled = spotify_audio_features_filled,
    audio_analysis_url = spotify_analysis_url,
    audio_track_href = spotify_track_href,
    audio_track_uri = spotify_uri,
    audio_feature_type = spotify_feature_type,
    audio_duration_ms = spotify_duration_ms,
    audio_key = spotify_key,
    audio_mode = spotify_mode,
    audio_time_signature = spotify_time_signature,
    audio_acousticness = spotify_acousticness,
    audio_danceability = spotify_danceability,
    audio_energy = spotify_energy,
    audio_instrumentalness = spotify_instrumentalness,
    audio_liveness = spotify_liveness,
    audio_loudness = spotify_loudness,
    audio_speechiness = spotify_speechiness,
    audio_tempo = spotify_tempo,
    audio_valence = spotify_valence,
    audio_resolved_at = spotify_resolved_at;

ALTER TABLE pms_user_track
    ADD COLUMN audio_feature_track_id VARCHAR(100),
    ADD COLUMN audio_feature_source VARCHAR(50) NOT NULL DEFAULT 'unresolved',
    ADD COLUMN audio_features_filled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN audio_analysis_url VARCHAR(300),
    ADD COLUMN audio_track_href VARCHAR(300),
    ADD COLUMN audio_track_uri VARCHAR(200),
    ADD COLUMN audio_feature_type VARCHAR(30) NOT NULL DEFAULT 'audio_features',
    ADD COLUMN audio_duration_ms INTEGER,
    ADD COLUMN audio_key INTEGER,
    ADD COLUMN audio_mode INTEGER,
    ADD COLUMN audio_time_signature INTEGER,
    ADD COLUMN audio_acousticness DOUBLE PRECISION,
    ADD COLUMN audio_danceability DOUBLE PRECISION,
    ADD COLUMN audio_energy DOUBLE PRECISION,
    ADD COLUMN audio_instrumentalness DOUBLE PRECISION,
    ADD COLUMN audio_liveness DOUBLE PRECISION,
    ADD COLUMN audio_loudness DOUBLE PRECISION,
    ADD COLUMN audio_speechiness DOUBLE PRECISION,
    ADD COLUMN audio_tempo DOUBLE PRECISION,
    ADD COLUMN audio_valence DOUBLE PRECISION,
    ADD COLUMN audio_resolved_at TIMESTAMPTZ;

UPDATE pms_user_track
SET
    audio_feature_track_id = spotify_track_id,
    audio_feature_source = spotify_audio_feature_source,
    audio_features_filled = spotify_audio_features_filled,
    audio_analysis_url = spotify_analysis_url,
    audio_track_href = spotify_track_href,
    audio_track_uri = spotify_uri,
    audio_feature_type = spotify_feature_type,
    audio_duration_ms = spotify_duration_ms,
    audio_key = spotify_key,
    audio_mode = spotify_mode,
    audio_time_signature = spotify_time_signature,
    audio_acousticness = spotify_acousticness,
    audio_danceability = spotify_danceability,
    audio_energy = spotify_energy,
    audio_instrumentalness = spotify_instrumentalness,
    audio_liveness = spotify_liveness,
    audio_loudness = spotify_loudness,
    audio_speechiness = spotify_speechiness,
    audio_tempo = spotify_tempo,
    audio_valence = spotify_valence,
    audio_resolved_at = spotify_resolved_at;

ALTER TABLE pms_imported_track
    ALTER COLUMN spotify_audio_feature_source SET DEFAULT 'unresolved',
    ALTER COLUMN spotify_audio_features_filled SET DEFAULT FALSE,
    ALTER COLUMN spotify_feature_type SET DEFAULT 'audio_features';

ALTER TABLE pms_user_track
    ALTER COLUMN spotify_audio_feature_source SET DEFAULT 'unresolved',
    ALTER COLUMN spotify_audio_features_filled SET DEFAULT FALSE,
    ALTER COLUMN spotify_feature_type SET DEFAULT 'audio_features';
