ALTER TABLE pms_track
    ADD COLUMN spotify_track_id VARCHAR(100),
    ADD COLUMN spotify_audio_feature_source VARCHAR(50) NOT NULL DEFAULT 'unresolved',
    ADD COLUMN spotify_audio_features_filled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN spotify_analysis_url VARCHAR(300),
    ADD COLUMN spotify_track_href VARCHAR(300),
    ADD COLUMN spotify_uri VARCHAR(200),
    ADD COLUMN spotify_feature_type VARCHAR(30) NOT NULL DEFAULT 'audio_features',
    ADD COLUMN spotify_duration_ms INTEGER,
    ADD COLUMN spotify_key INTEGER,
    ADD COLUMN spotify_mode INTEGER,
    ADD COLUMN spotify_time_signature INTEGER,
    ADD COLUMN spotify_acousticness NUMERIC(5,4),
    ADD COLUMN spotify_danceability NUMERIC(5,4),
    ADD COLUMN spotify_energy NUMERIC(5,4),
    ADD COLUMN spotify_instrumentalness NUMERIC(8,7),
    ADD COLUMN spotify_liveness NUMERIC(5,4),
    ADD COLUMN spotify_loudness NUMERIC(6,3),
    ADD COLUMN spotify_speechiness NUMERIC(5,4),
    ADD COLUMN spotify_tempo NUMERIC(7,3),
    ADD COLUMN spotify_valence NUMERIC(5,4),
    ADD COLUMN spotify_resolved_at TIMESTAMPTZ;

UPDATE pms_track
SET
    spotify_track_id = 'sp-track-alpha',
    spotify_audio_feature_source = 'spotify_api',
    spotify_audio_features_filled = TRUE,
    spotify_analysis_url = 'https://api.spotify.com/v1/audio-analysis/sp-track-alpha',
    spotify_track_href = 'https://api.spotify.com/v1/tracks/sp-track-alpha',
    spotify_uri = 'spotify:track:sp-track-alpha',
    spotify_feature_type = 'audio_features',
    spotify_duration_ms = 213000,
    spotify_key = 9,
    spotify_mode = 1,
    spotify_time_signature = 4,
    spotify_acousticness = 0.1820,
    spotify_danceability = 0.7420,
    spotify_energy = 0.8110,
    spotify_instrumentalness = 0.0000,
    spotify_liveness = 0.1110,
    spotify_loudness = -5.421,
    spotify_speechiness = 0.0450,
    spotify_tempo = 118.420,
    spotify_valence = 0.6840,
    spotify_resolved_at = '2026-05-03T00:00:00Z'
WHERE track_id = 'track-alpha';

UPDATE pms_track
SET
    spotify_track_id = 'sp-track-beta',
    spotify_audio_feature_source = 'spotify_match',
    spotify_audio_features_filled = TRUE,
    spotify_analysis_url = 'https://api.spotify.com/v1/audio-analysis/sp-track-beta',
    spotify_track_href = 'https://api.spotify.com/v1/tracks/sp-track-beta',
    spotify_uri = 'spotify:track:sp-track-beta',
    spotify_feature_type = 'audio_features',
    spotify_duration_ms = 221000,
    spotify_key = 2,
    spotify_mode = 1,
    spotify_time_signature = 4,
    spotify_acousticness = 0.2980,
    spotify_danceability = 0.6580,
    spotify_energy = 0.6330,
    spotify_instrumentalness = 0.0004,
    spotify_liveness = 0.1420,
    spotify_loudness = -6.118,
    spotify_speechiness = 0.0380,
    spotify_tempo = 109.880,
    spotify_valence = 0.5710,
    spotify_resolved_at = '2026-05-03T00:01:00Z'
WHERE track_id = 'track-beta';

UPDATE pms_track
SET
    spotify_track_id = 'sp-track-gamma',
    spotify_audio_feature_source = 'spotify_api',
    spotify_audio_features_filled = TRUE,
    spotify_analysis_url = 'https://api.spotify.com/v1/audio-analysis/sp-track-gamma',
    spotify_track_href = 'https://api.spotify.com/v1/tracks/sp-track-gamma',
    spotify_uri = 'spotify:track:sp-track-gamma',
    spotify_feature_type = 'audio_features',
    spotify_duration_ms = 205000,
    spotify_key = 7,
    spotify_mode = 1,
    spotify_time_signature = 4,
    spotify_acousticness = 0.1210,
    spotify_danceability = 0.7010,
    spotify_energy = 0.7740,
    spotify_instrumentalness = 0.0120,
    spotify_liveness = 0.0960,
    spotify_loudness = -5.764,
    spotify_speechiness = 0.0520,
    spotify_tempo = 122.540,
    spotify_valence = 0.6280,
    spotify_resolved_at = '2026-05-03T00:02:00Z'
WHERE track_id = 'track-gamma';

UPDATE pms_track
SET
    spotify_track_id = 'sp-track-delta',
    spotify_audio_feature_source = 'spotify_match',
    spotify_audio_features_filled = TRUE,
    spotify_analysis_url = 'https://api.spotify.com/v1/audio-analysis/sp-track-delta',
    spotify_track_href = 'https://api.spotify.com/v1/tracks/sp-track-delta',
    spotify_uri = 'spotify:track:sp-track-delta',
    spotify_feature_type = 'audio_features',
    spotify_duration_ms = 231000,
    spotify_key = 11,
    spotify_mode = 0,
    spotify_time_signature = 4,
    spotify_acousticness = 0.0830,
    spotify_danceability = 0.5920,
    spotify_energy = 0.7190,
    spotify_instrumentalness = 0.1030,
    spotify_liveness = 0.1320,
    spotify_loudness = -7.031,
    spotify_speechiness = 0.0410,
    spotify_tempo = 124.160,
    spotify_valence = 0.4370,
    spotify_resolved_at = '2026-05-03T00:03:00Z'
WHERE track_id = 'track-delta';

UPDATE pms_track
SET
    spotify_track_id = 'sp-track-epsilon',
    spotify_audio_feature_source = 'spotify_match',
    spotify_audio_features_filled = TRUE,
    spotify_analysis_url = 'https://api.spotify.com/v1/audio-analysis/sp-track-epsilon',
    spotify_track_href = 'https://api.spotify.com/v1/tracks/sp-track-epsilon',
    spotify_uri = 'spotify:track:sp-track-epsilon',
    spotify_feature_type = 'audio_features',
    spotify_duration_ms = 244000,
    spotify_key = 4,
    spotify_mode = 1,
    spotify_time_signature = 4,
    spotify_acousticness = 0.6120,
    spotify_danceability = 0.5110,
    spotify_energy = 0.4020,
    spotify_instrumentalness = 0.0810,
    spotify_liveness = 0.1180,
    spotify_loudness = -9.642,
    spotify_speechiness = 0.0330,
    spotify_tempo = 92.440,
    spotify_valence = 0.3490,
    spotify_resolved_at = '2026-05-03T00:04:00Z'
WHERE track_id = 'track-epsilon';

UPDATE pms_track
SET
    spotify_track_id = 'sp-track-zeta',
    spotify_audio_feature_source = 'spotify_api',
    spotify_audio_features_filled = TRUE,
    spotify_analysis_url = 'https://api.spotify.com/v1/audio-analysis/sp-track-zeta',
    spotify_track_href = 'https://api.spotify.com/v1/tracks/sp-track-zeta',
    spotify_uri = 'spotify:track:sp-track-zeta',
    spotify_feature_type = 'audio_features',
    spotify_duration_ms = 198000,
    spotify_key = 1,
    spotify_mode = 0,
    spotify_time_signature = 4,
    spotify_acousticness = 0.3540,
    spotify_danceability = 0.6240,
    spotify_energy = 0.4880,
    spotify_instrumentalness = 0.2140,
    spotify_liveness = 0.0870,
    spotify_loudness = -8.904,
    spotify_speechiness = 0.0290,
    spotify_tempo = 97.210,
    spotify_valence = 0.2910,
    spotify_resolved_at = '2026-05-03T00:05:00Z'
WHERE track_id = 'track-zeta';

UPDATE pms_track
SET
    spotify_track_id = 'sp-track-eta',
    spotify_audio_feature_source = 'spotify_match',
    spotify_audio_features_filled = TRUE,
    spotify_analysis_url = 'https://api.spotify.com/v1/audio-analysis/sp-track-eta',
    spotify_track_href = 'https://api.spotify.com/v1/tracks/sp-track-eta',
    spotify_uri = 'spotify:track:sp-track-eta',
    spotify_feature_type = 'audio_features',
    spotify_duration_ms = 227000,
    spotify_key = 8,
    spotify_mode = 1,
    spotify_time_signature = 5,
    spotify_acousticness = 0.2660,
    spotify_danceability = 0.5470,
    spotify_energy = 0.5610,
    spotify_instrumentalness = 0.0650,
    spotify_liveness = 0.1740,
    spotify_loudness = -8.117,
    spotify_speechiness = 0.0370,
    spotify_tempo = 105.660,
    spotify_valence = 0.3820,
    spotify_resolved_at = '2026-05-03T00:06:00Z'
WHERE track_id = 'track-eta';

UPDATE pms_track
SET
    spotify_track_id = 'sp-track-theta',
    spotify_audio_feature_source = 'spotify_api',
    spotify_audio_features_filled = TRUE,
    spotify_analysis_url = 'https://api.spotify.com/v1/audio-analysis/sp-track-theta',
    spotify_track_href = 'https://api.spotify.com/v1/tracks/sp-track-theta',
    spotify_uri = 'spotify:track:sp-track-theta',
    spotify_feature_type = 'audio_features',
    spotify_duration_ms = 216000,
    spotify_key = 6,
    spotify_mode = 1,
    spotify_time_signature = 4,
    spotify_acousticness = 0.4410,
    spotify_danceability = 0.5830,
    spotify_energy = 0.5360,
    spotify_instrumentalness = 0.0040,
    spotify_liveness = 0.1090,
    spotify_loudness = -7.442,
    spotify_speechiness = 0.0340,
    spotify_tempo = 102.340,
    spotify_valence = 0.4720,
    spotify_resolved_at = '2026-05-03T00:07:00Z'
WHERE track_id = 'track-theta';

UPDATE pms_track
SET
    spotify_track_id = 'sp-track-iota',
    spotify_audio_feature_source = 'spotify_match',
    spotify_audio_features_filled = TRUE,
    spotify_analysis_url = 'https://api.spotify.com/v1/audio-analysis/sp-track-iota',
    spotify_track_href = 'https://api.spotify.com/v1/tracks/sp-track-iota',
    spotify_uri = 'spotify:track:sp-track-iota',
    spotify_feature_type = 'audio_features',
    spotify_duration_ms = 209000,
    spotify_key = 10,
    spotify_mode = 1,
    spotify_time_signature = 4,
    spotify_acousticness = 0.1570,
    spotify_danceability = 0.7360,
    spotify_energy = 0.7820,
    spotify_instrumentalness = 0.0001,
    spotify_liveness = 0.0910,
    spotify_loudness = -5.989,
    spotify_speechiness = 0.0480,
    spotify_tempo = 120.730,
    spotify_valence = 0.6610,
    spotify_resolved_at = '2026-05-03T00:08:00Z'
WHERE track_id = 'track-iota';

UPDATE pms_track
SET
    spotify_track_id = 'sp-track-kappa',
    spotify_audio_feature_source = 'spotify_match',
    spotify_audio_features_filled = TRUE,
    spotify_analysis_url = 'https://api.spotify.com/v1/audio-analysis/sp-track-kappa',
    spotify_track_href = 'https://api.spotify.com/v1/tracks/sp-track-kappa',
    spotify_uri = 'spotify:track:sp-track-kappa',
    spotify_feature_type = 'audio_features',
    spotify_duration_ms = 238000,
    spotify_key = 3,
    spotify_mode = 0,
    spotify_time_signature = 4,
    spotify_acousticness = 0.0940,
    spotify_danceability = 0.6040,
    spotify_energy = 0.6870,
    spotify_instrumentalness = 0.1430,
    spotify_liveness = 0.1530,
    spotify_loudness = -7.553,
    spotify_speechiness = 0.0420,
    spotify_tempo = 126.980,
    spotify_valence = 0.4180,
    spotify_resolved_at = '2026-05-03T00:09:00Z'
WHERE track_id = 'track-kappa';

UPDATE pms_track
SET
    spotify_track_id = 'sp-track-lambda',
    spotify_audio_feature_source = 'spotify_match',
    spotify_audio_features_filled = TRUE,
    spotify_analysis_url = 'https://api.spotify.com/v1/audio-analysis/sp-track-lambda',
    spotify_track_href = 'https://api.spotify.com/v1/tracks/sp-track-lambda',
    spotify_uri = 'spotify:track:sp-track-lambda',
    spotify_feature_type = 'audio_features',
    spotify_duration_ms = 252000,
    spotify_key = 0,
    spotify_mode = 0,
    spotify_time_signature = 4,
    spotify_acousticness = 0.4880,
    spotify_danceability = 0.4620,
    spotify_energy = 0.3510,
    spotify_instrumentalness = 0.3320,
    spotify_liveness = 0.0820,
    spotify_loudness = -10.416,
    spotify_speechiness = 0.0280,
    spotify_tempo = 88.560,
    spotify_valence = 0.2210,
    spotify_resolved_at = '2026-05-03T00:10:00Z'
WHERE track_id = 'track-lambda';

UPDATE pms_track
SET
    spotify_track_id = 'sp-track-mu',
    spotify_audio_feature_source = 'spotify_api',
    spotify_audio_features_filled = TRUE,
    spotify_analysis_url = 'https://api.spotify.com/v1/audio-analysis/sp-track-mu',
    spotify_track_href = 'https://api.spotify.com/v1/tracks/sp-track-mu',
    spotify_uri = 'spotify:track:sp-track-mu',
    spotify_feature_type = 'audio_features',
    spotify_duration_ms = 223000,
    spotify_key = 5,
    spotify_mode = 1,
    spotify_time_signature = 4,
    spotify_acousticness = 0.0710,
    spotify_danceability = 0.6880,
    spotify_energy = 0.8070,
    spotify_instrumentalness = 0.0090,
    spotify_liveness = 0.1270,
    spotify_loudness = -5.102,
    spotify_speechiness = 0.0430,
    spotify_tempo = 116.250,
    spotify_valence = 0.5340,
    spotify_resolved_at = '2026-05-03T00:11:00Z'
WHERE track_id = 'track-mu';

ALTER TABLE pms_track
    ALTER COLUMN spotify_duration_ms SET NOT NULL,
    ALTER COLUMN spotify_key SET NOT NULL,
    ALTER COLUMN spotify_mode SET NOT NULL,
    ALTER COLUMN spotify_time_signature SET NOT NULL,
    ALTER COLUMN spotify_acousticness SET NOT NULL,
    ALTER COLUMN spotify_danceability SET NOT NULL,
    ALTER COLUMN spotify_energy SET NOT NULL,
    ALTER COLUMN spotify_instrumentalness SET NOT NULL,
    ALTER COLUMN spotify_liveness SET NOT NULL,
    ALTER COLUMN spotify_loudness SET NOT NULL,
    ALTER COLUMN spotify_speechiness SET NOT NULL,
    ALTER COLUMN spotify_tempo SET NOT NULL,
    ALTER COLUMN spotify_valence SET NOT NULL,
    ALTER COLUMN spotify_resolved_at SET NOT NULL;
